Feature of basic && commands
AY2122S2-CS2103-W17-1/tp pull request #143
Opened 2022-03-08 15:56 UTC by HanJiyao

Basic functionality only, currently excute all and returns the last feedback

2022-03-08 17:20 UTC, sharpstorm reviewed
Could you do some test cases for this?

2022-03-09 11:52 UTC, sharpstorm requested changes
Small issue, but looks good otherwise

2022-03-09 11:52 UTC, sharpstorm commented on src/test/java/seedu/contax/logic/parser/ChainCommandParseTest.java
> +public class ChainCommandParseTest {
Please check this file name.
```suggestion
public class ChainCommandParserTest {
```

2022-03-09 12:09 UTC, HanJiyao commented on src/test/java/seedu/contax/logic/parser/ChainCommandParseTest.java
> +public class ChainCommandParseTest {
thx changed alr

2022-03-09 12:13 UTC, sharpstorm approved these changes
LGTM.

2022-03-09 12:36 UTC, dandaandaaaaaan approved these changes
lgtm! thanks

2022-03-09 12:37 UTC, merged